### ISSUE TITLE
Unable to use buckets specified as dict

### ISSUE THREAD

**Issue by ricecooker** [line/jnotebook_reader#14]
https://github.com/line/jnotebook_reader/blob/b72d3e71560c724fb22d21c62413b205f00cc786/renderer/s3/s3.py#L51-L53

When`lib/config.py` uses a `dict` to specify buckets, the code above has a typecast exception casting a string to an int even when `JNOTEBOOK_READER_S3_BUCKET_NAME` is not used. As a result, buckets specified as a dict does not work currently in jnotebook_reader.

**Comment by mars-martin-line** [comment]
Merged
